# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\x1e\n\x0b\x44\x61taRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\"\x1c\n\x0c\x44\x61taResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32G\n\x0b\x44\x61taService\x12\x38\n\x07GetData\x12\x14.example.DataRequest\x1a\x15.example.DataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=26
  _globals['_DATAREQUEST']._serialized_end=56
  _globals['_DATARESPONSE']._serialized_start=58
  _globals['_DATARESPONSE']._serialized_end=86
  _globals['_DATASERVICE']._serialized_start=88
  _globals['_DATASERVICE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
