# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interceptor_example.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19interceptor_example.proto\x12\x13interceptor_example\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x0b\x45\x63hoService\x12K\n\x04\x45\x63ho\x12 .interceptor_example.EchoRequest\x1a!.interceptor_example.EchoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interceptor_example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=50
  _globals['_ECHOREQUEST']._serialized_end=80
  _globals['_ECHORESPONSE']._serialized_start=82
  _globals['_ECHORESPONSE']._serialized_end=113
  _globals['_ECHOSERVICE']._serialized_start=115
  _globals['_ECHOSERVICE']._serialized_end=205
# @@protoc_insertion_point(module_scope)
